# DEBUG				:= false

# PROPERTY := SPR
# PROPERTY := RAT

# ITERATIONS			:= 0

# REDUNDANCY_CHECK 		:= UNIT_IMPLICATION
# REDUNDANCY_CHECK 		:= SUBSUMPTION
# ASSIGNMENT_LIMIT		:= 0
# WATCH_LITERALS		:= false

# SORT_CLAUSES			:= false
# SORT_CLAUSES			:= SIZE_ASCENDINGLY	
# SORT_CLAUSES			:= SIZE_DESCENDINGLY

# SORT_CLAUSE_LITERALS		:= false
# SORT_CLAUSE_LITERALS		:= ASCENDINGLY
# SORT_CLAUSE_LITERALS		:= MAG_SIGN

# SORT_VARIABLE_OCCURRENCES	:= true

# STORE_REFUTATIONS		:= true
# DETECT_ENVIRONMENT_CHANGE	:= true

# PARALLEL			:= false
# PARALLEL			:= PTHREADS
# THREADS			:= 4
# PARALLEL			:= CILK
# PARALLEL			:= LACE

# SMALL_CLAUSE_OPTIMIZATION	:= true
# SMALL_CLAUSE_SIZE		:= 10

# LOG_L_SIZES			:= false

# MEMBERSHIP_MATRIX		:= false
# MEMBERSHIP_MATRIX		:= CLAUSE_LITERAL
# MEMBERSHIP_MATRIX		:= LITERAL_CLAUSE
# DENSE_MEMBERSHIP_MATRIX	:= true

# RESOLVENT_LITERAL_MAP		:= false
